#!/usr/bin/env bash
#
# Generate the -git PKGBUILDs for the application suite from apps.txt.
#
# Every app in the suite uses the same COSMIC justfile contract — `rootdir`,
# `prefix`, `build-release`, `install`, `vendor` — so the PKGBUILDs are
# genuinely identical apart from name, description and dependencies. They are
# generated rather than hand-maintained so a packaging fix lands in one place.
#
# The generated files ARE committed: they are what makepkg reads, and a
# reviewer should see the same text the build sees.
set -euo pipefail

root="$(cd "$(dirname "$0")/.." && pwd)"
manifest="$root/pkgbuilds/apps/apps.txt"
count=0


while IFS='|' read -r name desc extradeps extraopt; do
  [[ -n ${name:-} && $name != \#* ]] || continue

  dir="$root/pkgbuilds/apps/$name-git"
  mkdir -p "$dir"
  url="git+https://github.com/Magnetar-OS/$name.git"

  deps="'glib2' 'libxkbcommon' 'systemd-libs' 'zlib'"
  for d in $extradeps; do deps+=" '$d'"; done

  opt=""
  if [[ -n ${extraopt:-} ]]; then
    IFS=',' read -ra parts <<< "$extraopt"
    for p in "${parts[@]}"; do
      [[ -n $p ]] && opt+="  '$p'"$'\n'
    done
  fi

  {
    cat <<EOF
# Maintainer: Dominikos Pritis <hey@myroomie.gr>
#
# GENERATED by tools/gen-app-pkgbuilds.sh from pkgbuilds/apps/apps.txt.
# Edit the manifest or the generator, not this file.
#
# A -git package because $name is not tagged yet. When it cuts a release,
# linux-release-kit publishes a versioned package to [magnetar] and this
# one should be deleted, not kept alongside it.
pkgname=$name-git
_pkgname=$name
pkgver=0.1.0.r0.gHEAD
pkgrel=1
pkgdesc="$desc"
arch=('x86_64' 'aarch64')
url="https://github.com/Magnetar-OS/$name"
license=('GPL-3.0-or-later')

# The libcosmic base set, derived from what installed COSMIC applications
# actually link against rather than from reading Cargo.toml. Anything else is
# per-app and comes from namcap against a real build — CI reports it.
depends=($deps)

# Unversioned on purpose: rustup provides rust and cargo without a version, so
# a versioned makedepend can never be satisfied on a machine using it. The
# real minimum is rust-version in Cargo.toml, and cargo says so plainly.
makedepends=('cargo' 'git' 'just' 'pkgconf')
EOF

    if [[ -n $opt ]]; then
      printf '\noptdepends=(\n%s)\n' "$opt"
    fi

    cat <<EOF

provides=('$name')
conflicts=('$name')
source=("\$pkgname::$url")
sha256sums=('SKIP')
options=('!lto')  # the workspace sets its own lto profile in Cargo.toml

pkgver() {
  cd "\$srcdir/\$pkgname"
  # <cargo version>.r<commits>.g<hash> — sorts correctly and names the commit.
  printf "%s.r%s.g%s" \\
    "\$(awk -F'"' '/^version/ {print \$2; exit}' Cargo.toml)" \\
    "\$(git rev-list --count HEAD)" \\
    "\$(git rev-parse --short HEAD)"
}

prepare() {
  cd "\$srcdir/\$pkgname"
  export RUSTUP_TOOLCHAIN=stable
  # Fetch now so build() runs offline, which is what makechrootpkg expects.
  cargo fetch --locked --target "\$(rustc -vV | sed -n 's/host: //p')"
}

build() {
  cd "\$srcdir/\$pkgname"
  export RUSTUP_TOOLCHAIN=stable
  export CARGO_TARGET_DIR=target

  # CachyOS ships /etc/makepkg.conf.d/rust.conf with
  #   RUSTFLAGS="-C opt-level=3 -C target-cpu=native"
  # which is right for a machine compiling for itself and wrong for a package
  # other people install: the binary then uses whatever ISA extensions the
  # build host happened to have and SIGILLs on anything older. Pin the generic
  # baseline. CPU-optimised builds are what the CachyOS v3/v4 repositories are
  # for, and a Magnetar user gets them the same way a CachyOS user does.
  export RUSTFLAGS="-C opt-level=3"

  just build-release
}

check() {
  cd "\$srcdir/\$pkgname"
  export RUSTUP_TOOLCHAIN=stable
  export CARGO_TARGET_DIR=target
  export RUSTFLAGS="-C opt-level=3"
  # No display, no compositor, no session bus in a build chroot. Tests that
  # need one are expected to be #[ignore]d upstream; if this fails, fix the
  # test rather than deleting check().
  cargo test --frozen --workspace
}

package() {
  cd "\$srcdir/\$pkgname"
  export CARGO_TARGET_DIR=target
  # The justfile owns the file list. Every app in the suite honours rootdir
  # and prefix, so the packager never has to restate where things go — and
  # never drifts from upstream when a file is added.
  just rootdir="\$pkgdir" prefix=/usr install

  install -Dm644 LICENSE "\$pkgdir/usr/share/licenses/\$pkgname/LICENSE" 2>/dev/null \\
    || install -Dm644 LICENSE.md "\$pkgdir/usr/share/licenses/\$pkgname/LICENSE"
}
EOF
  } > "$dir/PKGBUILD"

  count=$((count+1))
  echo "  generated $name-git"
done < "$manifest"

echo "$count PKGBUILDs generated"
