#!/usr/bin/env bash
#
# Generate PKGBUILDs that build the suite from LOCAL WORKING TREES.
#
# Development and ISO-testing only. The committed PKGBUILDs in pkgbuilds/apps
# build from GitHub and are what ships; these exist because right now the suite
# cannot be built any other way:
#
#   - peek and grabit have no commits at all, so a git clone yields an empty
#     repository.
#   - circle, slate and envelope depend on siblings by path
#     (`cosmic-pim-core = { path = "../cosmic-pim/crates/cosmic-pim-core" }`),
#     so cloning one repository alone can never resolve its dependencies.
#     Their own Cargo.toml says "Paths until cosmic-pim is pushed".
#
# So these stage the app plus every sibling it references into $srcdir and
# build there. Output goes to build/pkgbuilds-local/ and is gitignored: it
# embeds absolute paths and builds from a possibly-dirty tree, which is exactly
# what a released package must never do.
#
#   tools/gen-app-pkgbuilds-local.sh [source-root]   (default ~/GitHub)
set -euo pipefail

root="$(cd "$(dirname "$0")/.." && pwd)"
src_root="$(cd "${1:-$HOME/GitHub}" && pwd)"
manifest="$root/pkgbuilds/apps/apps.txt"
outbase="$root/build/pkgbuilds-local"
count=0

echo "source root: $src_root"

while IFS='|' read -r name desc extradeps _extraopt; do
  [[ -n ${name:-} && $name != \#* ]] || continue
  [[ -f $src_root/$name/Cargo.toml ]] || { echo "  SKIP $name: no working tree" >&2; continue; }

  # Siblings the app references by relative path. Read out of Cargo.toml
  # rather than listed here: the set changes as the suite is refactored, and a
  # stale list fails as a confusing dependency error deep in a build log.
  mapfile -t sibs < <(grep -oE 'path = "\.\./[A-Za-z0-9_-]+' "$src_root/$name/Cargo.toml" \
                       | sed 's|path = "\.\./||' | sort -u)
  for s in "${sibs[@]}"; do
    [[ -d $src_root/$s ]] || { echo "  WARN $name: sibling '$s' missing at $src_root/$s" >&2; }
  done

  deps="'glib2' 'libxkbcommon' 'systemd-libs' 'zlib'"
  for d in $extradeps; do deps+=" '$d'"; done

  dir="$outbase/$name-git"
  mkdir -p "$dir"

  {
    cat <<EOF
# GENERATED by tools/gen-app-pkgbuilds-local.sh — do not edit, do not commit.
#
# Builds $name from the working tree at $src_root/$name, staging the siblings
# it references by path. Absolute paths and a possibly-dirty tree: fine for a
# VM image, never for a published package.
pkgname=$name-git
pkgver=0.1.0.r0.local
pkgrel=1
pkgdesc="$desc"
arch=('x86_64')
url="https://magnetaros.com"
license=('GPL-3.0-or-later')
depends=($deps)
makedepends=('cargo' 'git' 'just' 'pkgconf' 'rsync')
provides=('$name')
conflicts=('$name')
options=('!lto' '!debug')

_src_root='$src_root'
_app='$name'
_sibs=($(printf "'%s' " "${sibs[@]}"))

# No source=(): the sources are working trees, staged in prepare().
source=()
sha256sums=()

pkgver() {
  # No git describe: two of these repositories have no commits. Version from
  # Cargo.toml plus a build date, which is honest about what this is.
  local v
  v="\$(awk -F'"' '/^version/ {print \$2; exit}' "\$_src_root/\$_app/Cargo.toml")"
  printf '%s.r0.%s' "\${v:-0.1.0}" "\$(date +%Y%m%d)"
}

prepare() {
  rm -rf "\$srcdir/tree"
  mkdir -p "\$srcdir/tree"
  # --exclude target: the working trees carry multi-gigabyte build directories.
  # --exclude .git: nothing in the build reads history.
  for m in "\$_app" "\${_sibs[@]}"; do
    [[ -d "\$_src_root/\$m" ]] || continue
    rsync -a --exclude target --exclude .git "\$_src_root/\$m/" "\$srcdir/tree/\$m/"
  done
}

build() {
  cd "\$srcdir/tree/\$_app"
  export RUSTUP_TOOLCHAIN=stable
  export CARGO_TARGET_DIR=target
  # CachyOS's /etc/makepkg.conf.d/rust.conf sets -C target-cpu=native, which
  # would make this binary SIGILL on any CPU older than the build host.
  export RUSTFLAGS="-C opt-level=3"
  just build-release
}

package() {
  cd "\$srcdir/tree/\$_app"
  export CARGO_TARGET_DIR=target
  just rootdir="\$pkgdir" prefix=/usr install
  install -Dm644 LICENSE "\$pkgdir/usr/share/licenses/\$pkgname/LICENSE" 2>/dev/null \\
    || install -Dm644 LICENSE.md "\$pkgdir/usr/share/licenses/\$pkgname/LICENSE" 2>/dev/null \\
    || true
}
EOF
  } > "$dir/PKGBUILD"

  count=$((count+1))
  printf '  %-12s siblings: %s\n' "$name" "${sibs[*]:-none}"
done < "$manifest"

# --- locket ----------------------------------------------------------------
# locket is not in apps.txt on purpose: it has a hand-written PKGBUILD at
# locket/packaging/arch/PKGBUILD whose dependency list was derived from what its
# binaries actually link against, which beats anything generated. That PKGBUILD
# sources from GitHub, where locket is not published, so it cannot be used
# as-is for a local build.
#
# So: reuse its depends line, and emit the same local template as the rest.
# The template is a quoted heredoc — the $-variables in it belong to the
# generated PKGBUILD, not to this script — with the two varying values
# substituted afterwards.
if [[ -f $src_root/locket/packaging/arch/PKGBUILD ]]; then
  # Read the array by sourcing the PKGBUILD in a subshell rather than parsing
  # it. A sed range over `depends=(...)` silently over-runs when the array is
  # on one line, and bash is the only thing that reliably parses bash.
  locket_deps=$(bash -c '
      set -e
      source "$1" >/dev/null 2>&1 || true
      for d in "${depends[@]}"; do printf "'"'"'%s'"'"' " "$d"; done
    ' _ "$src_root/locket/packaging/arch/PKGBUILD")
  dir="$outbase/locket-git"
  mkdir -p "$dir"
  cat > "$dir/PKGBUILD" <<'LOCKET_TEMPLATE'
# GENERATED by tools/gen-app-pkgbuilds-local.sh — do not edit, do not commit.
#
# depends is copied from @SRCROOT@/locket/packaging/arch/PKGBUILD, which lists
# what the binaries actually link against. Everything else follows the same
# local template as the rest of the suite.
pkgname=locket-git
pkgver=0.1.0.r0.local
pkgrel=1
pkgdesc="Password and secrets manager for COSMIC: Secret Service, Secret portal and SSH agent"
arch=('x86_64')
url="https://magnetaros.com"
license=('GPL-3.0-or-later')
depends=(@DEPENDS@)
makedepends=('cargo' 'git' 'just' 'pkgconf' 'rsync')
provides=('locket')
conflicts=('locket')
options=('!lto' '!debug')

_src_root='@SRCROOT@'
_app='locket'
source=()
sha256sums=()

pkgver() {
  local v
  v="$(awk -F'"' '/^version/ {print $2; exit}' "$_src_root/$_app/Cargo.toml")"
  printf '%s.r0.%s' "${v:-0.1.0}" "$(date +%Y%m%d)"
}

prepare() {
  rm -rf "$srcdir/tree"
  mkdir -p "$srcdir/tree"
  rsync -a --exclude target --exclude .git "$_src_root/$_app/" "$srcdir/tree/$_app/"
}

build() {
  cd "$srcdir/tree/$_app"
  export RUSTUP_TOOLCHAIN=stable
  export CARGO_TARGET_DIR=target
  # CachyOS's rust.conf sets -C target-cpu=native; that would SIGILL elsewhere.
  export RUSTFLAGS="-C opt-level=3"
  just build-release
}

package() {
  cd "$srcdir/tree/$_app"
  export CARGO_TARGET_DIR=target
  just rootdir="$pkgdir" prefix=/usr install
}
LOCKET_TEMPLATE

  sed -i -e "s|@SRCROOT@|$src_root|g" -e "s|@DEPENDS@|$locket_deps|" "$dir/PKGBUILD"
  count=$((count+1))
  printf '  %-12s siblings: none (depends from its own PKGBUILD)\n' locket
fi

echo "$count local PKGBUILDs in $outbase"
